project:
  type: book
  output-dir: docs

book:
  title: "The JASP Video Library"
  author: "The JASP Team"
  chapters:
    - index.qmd
    - _qmd/0_Getting_Started.qmd
    - _qmd/1_Descriptives.qmd
    - _qmd/2_All_T-Tests.qmd
    - _qmd/3_All_ANOVA.qmd
    - _qmd/4_All_Regression.qmd
    - _qmd/5_All_Frequencies.qmd
    - _qmd/6_All_Factor.qmd
    - _qmd/7_Meta_Analysis.qmd
    - _qmd/8_Network_Analysis.qmd
    - _qmd/9_Mediation.qmd 

format:
  html:
    theme: bootstrap
  pdf:
    documentclass: scrreprt

editor: visual
new_session: no
url_sanitize: false

