project:
  type: book
  output-dir: docs
  resources:
  - assets

book:
  title: "The JASP Video Library"
  author: "The JASP Team"
  chapters:
    - index.qmd
    - Getting-Started.qmd
    - Descriptives.qmd
    - All_T-Tests.qmd
    - All_ANOVA.qmd
    - All_Regression.qmd
    - All_Frequencies.qmd
    - All_Factor-Analysis.qmd
    - Meta-Analysis.qmd
    - Network-Analysis.qmd
    - Mediation.qmd

format:
  html:
    theme: bootstrap
  pdf:
    documentclass: scrreprt

editor: visual
new_session: no
url_sanitize: false

