project:
  type: book
  output-dir: docs
  resources:
  - assets

book:
  title: "The JASP Video Library"
  author: "The JASP Team"
  chapters:
    - index.qmd
    - 0_Getting_Started.qmd
    - 1_Descriptives.qmd
    - 2_All_T-Tests.qmd
    - 3_All_ANOVA.qmd
    - 4_All_Regression.qmd
    - 5_All_Frequencies.qmd
    - 6_All_Factor.qmd
    - 7_Meta_Analysis.qmd
    - 8_Network_Analysis.qmd
    - 9_Mediation.qmd

format:
  html:
    theme: bootstrap
  pdf:
    documentclass: scrreprt

editor: visual
new_session: no
url_sanitize: false

