project:
  type: book
  output-dir: docs

book:
  title: "The JASP Video Library"
  author: "The JASP Team"
  chapters:
    - index.qmd
    - output.md

format:
  html:
    theme: bootstrap
  pdf:
    documentclass: scrreprt

editor: visual
new_session: no
url_sanitize: false

